'use client';
import {useEffect,useMemo,useState} from 'react'; import {supabaseBrowser} from '../lib/supabase-browser'; import RichEditor from './RichEditor';
function init(fields){return Object.fromEntries(fields.map(([k,,t])=>[k,t==='boolean'?true:'']))}
export default function ResourceEditor({cfg}){const sb=useMemo(()=>supabaseBrowser(),[]);const [rows,setRows]=useState([]);const [form,setForm]=useState(init(cfg.fields));const [editing,setEditing]=useState(null);const [msg,setMsg]=useState('');
 async function load(){const {data,error}=await sb.from(cfg.table).select('*').order('updated_at',{ascending:false});if(error)setMsg(error.message);else setRows(data||[])}
 useEffect(()=>{load()},[]);
 function change(k,t,v){setForm(f=>({...f,[k]:t==='boolean'?v:v}))}
 async function save(e){e.preventDefault();setMsg('Saving…');const payload={...form};if('tags' in payload && typeof payload.tags==='string')payload.tags=payload.tags.split(',').map(x=>x.trim()).filter(Boolean);Object.keys(payload).forEach(k=>{if(payload[k]==='')payload[k]=null});const q=editing?sb.from(cfg.table).update(payload).eq('id',editing):sb.from(cfg.table).insert(payload);const {error}=await q;if(error){setMsg(error.message);return}setMsg('Saved');setEditing(null);setForm(init(cfg.fields));load()}
 function edit(r){const x={};cfg.fields.forEach(([k,,t])=>{let v=r[k]??(t==='boolean'?false:'');if(k==='tags'&&Array.isArray(v))v=v.join(', ');if(t==='datetime-local'&&v)v=String(v).slice(0,16);x[k]=v});setForm(x);setEditing(r.id);window.scrollTo({top:0,behavior:'smooth'})}
 async function del(id){if(!confirm('Delete this item?'))return;const {error}=await sb.from(cfg.table).delete().eq('id',id);setMsg(error?error.message:'Deleted');load()}
 return <><div className="admin-top"><div className="admin-title"><h1>{cfg.title}</h1><p>Live database controls — changes persist immediately.</p></div></div><div className="resource-grid"><section className="admin-panel"><div className="panel-head"><b>{editing?'Edit item':'New item'}</b>{editing&&<button className="copy" onClick={()=>{setEditing(null);setForm(init(cfg.fields))}}>Cancel</button>}</div><form className="panel-body" onSubmit={save}>{cfg.fields.map(([k,label,t])=><div className="field" key={k}><label>{label}</label>{k==='content_html'?<RichEditor value={form[k]??''} onChange={v=>change(k,t,v)}/>:t==='textarea'?<textarea rows="5" value={form[k]??''} onChange={e=>change(k,t,e.target.value)}/>:t==='boolean'?<input type="checkbox" checked={!!form[k]} onChange={e=>change(k,t,e.target.checked)}/>:t.startsWith('select:')?<select value={form[k]??''} onChange={e=>change(k,t,e.target.value)}>{t.slice(7).split(',').map(o=><option key={o} value={o}>{o}</option>)}</select>:<input type={t} value={form[k]??''} onChange={e=>change(k,t,e.target.value)}/>}</div>)}<button className="primary">{editing?'Update':'Create'}</button><p className="notice">{msg}</p></form></section><section className="admin-panel"><div className="panel-head"><b>Existing items</b><span className="badge">{rows.length}</span></div><div className="panel-body resource-list">{rows.length===0&&<p className="notice">No items configured yet.</p>}{rows.map(r=><div className="resource-item" key={r.id}><div><b>{r.title||r.name||r.key||r.path||r.source_path||r.question||r.directive||'Item'}</b><div className="notice">{r.slug||r.page_path||r.destination_url||r.value||r.status||''}</div></div><div style={{display:'flex',gap:7}}><button className="copy" onClick={()=>edit(r)}>Edit</button><button className="danger" onClick={()=>del(r.id)}>Delete</button></div></div>)}</div></section></div></>}
